# Generated by Django 3.2.6 on 2021-08-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_merchandise'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='has_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True),
        ),
    ]
